PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TEXT NOT NULL DEFAULT(datetime('now')),last_seen TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,body TEXT NOT NULL,image_url TEXT DEFAULT '',category TEXT DEFAULT 'مود',author_id INTEGER,created_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,username TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS site_stats(id INTEGER PRIMARY KEY CHECK(id=1),visits INTEGER NOT NULL DEFAULT 0,downloads INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO site_stats(id) VALUES(1);
CREATE INDEX IF NOT EXISTS idx_posts ON posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat ON messages(created_at DESC);
