const enc = new TextEncoder();
const json = (data,status=200,origin='*') => new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','access-control-allow-origin':origin,'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'}});
const now=()=>new Date().toISOString();
async function hashPassword(p,salt){const key=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256);return btoa(String.fromCharCode(...new Uint8Array(bits)));}
async function sign(payload,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),'HMAC',false,['sign']);const body=btoa(JSON.stringify(payload)).replace(/=/g,'');const sig=await crypto.subtle.sign('HMAC',key,enc.encode(body));return body+'.'+btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/=/g,'');}
async function verify(token,secret){try{const [body,sig]=token.split('.');if(!body||!sig)return null;const key=await crypto.subtle.importKey('raw',enc.encode(secret),'HMAC',false,['verify']);const ok=await crypto.subtle.verify('HMAC',key,Uint8Array.from(atob(sig.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)),enc.encode(body));if(!ok)return null;const p=JSON.parse(atob(body));return p.exp>Date.now()/1000?p:null}catch{return null}}
async function auth(req,env){const h=req.headers.get('authorization')||'';const p=await verify(h.replace(/^Bearer\s+/i,''),env.JWT_SECRET||'change-this-secret');if(!p)return null;return await env.DB.prepare('SELECT id,username,email,role,avatar,bio,created_at,last_login FROM users WHERE id=?').bind(p.uid).first();}
async function stats(env){const row=await env.DB.prepare(`SELECT s.total_visits,s.total_downloads,s.total_users,s.online_now,(SELECT COUNT(*) FROM mods) mods,(SELECT COUNT(*) FROM packs) packs FROM site_stats s WHERE s.id=1`).first();return row||{total_visits:0,total_downloads:0,total_users:0,online_now:0,mods:0,packs:0};}
async function touch(env){await env.DB.prepare('UPDATE site_stats SET total_visits=total_visits+1 WHERE id=1').run();await env.DB.prepare("UPDATE sessions SET last_seen=? WHERE last_seen < datetime('now','-2 minutes')").bind(now()).run();}
async function api(req,env){const url=new URL(req.url);const path=url.pathname;const method=req.method;const origin=env.ALLOWED_ORIGIN||'*';if(method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':origin,'access-control-allow-headers':'Content-Type, Authorization','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS'}});
if(path==='/api/public'&&method==='GET'){await touch(env);const [mods,packs,cats,st]=await Promise.all([env.DB.prepare('SELECT * FROM mods ORDER BY featured DESC, id DESC').all(),env.DB.prepare('SELECT * FROM packs ORDER BY id DESC').all(),env.DB.prepare('SELECT * FROM categories ORDER BY id').all(),stats(env)]);return json({mods:mods.results,packs:packs.results,categories:cats.results,stats:st},200,origin)}
if(path==='/api/ping'&&method==='POST'){let sessionId=(await req.json().catch(()=>({}))).sessionId||crypto.randomUUID();await env.DB.prepare("INSERT INTO sessions(id,last_seen) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET last_seen=excluded.last_seen").bind(sessionId,now()).run();await env.DB.prepare("UPDATE site_stats SET online_now=(SELECT COUNT(*) FROM sessions WHERE last_seen >= datetime('now','-2 minutes')) WHERE id=1").run();return json({ok:true,sessionId,stats:await stats(env)},200,origin)}
if(path==='/api/register'&&method==='POST'){const b=await req.json();if(!b.username||!b.email||!b.password||b.password.length<6)return json({error:'اطلاعات ثبت‌نام کامل نیست یا رمز کوتاه است'},400,origin);const salt=crypto.randomUUID();const ph=await hashPassword(b.password,salt);try{const r=await env.DB.prepare('INSERT INTO users(username,email,password_hash) VALUES(?,?,?)').bind(b.username.trim(),b.email.trim().toLowerCase(),salt+':'+ph).run();await env.DB.prepare('UPDATE site_stats SET total_users=total_users+1 WHERE id=1').run();return json({ok:true},200,origin)}catch(e){return json({error:'نام کاربری یا ایمیل قبلاً ثبت شده است'},409,origin)}}
if(path==='/api/login'&&method==='POST'){const b=await req.json();const u=await env.DB.prepare('SELECT * FROM users WHERE email=? OR username=?').bind((b.identity||'').trim().toLowerCase(),(b.identity||'').trim()).first();if(!u)return json({error:'حساب پیدا نشد'},401,origin);const [salt,stored]=u.password_hash.split(':');if(await hashPassword(b.password,salt)!==stored)return json({error:'رمز عبور اشتباه است'},401,origin);await env.DB.prepare('UPDATE users SET last_login=? WHERE id=?').bind(now(),u.id).run();const token=await sign({uid:u.id,exp:Math.floor(Date.now()/1000)+60*60*24*14},env.JWT_SECRET||'change-this-secret');return json({token,user:{id:u.id,username:u.username,email:u.email,role:u.role,avatar:u.avatar,bio:u.bio}},200,origin)}
if(path==='/api/me'&&method==='GET'){const u=await auth(req,env);return u?json({user:u},200,origin):json({error:'unauthorized'},401,origin)}
if(path==='/api/download'&&method==='POST'){const b=await req.json();const u=await auth(req,env);if(b.mod_id){await env.DB.prepare('UPDATE mods SET downloads=downloads+1 WHERE id=?').bind(b.mod_id).run();await env.DB.prepare('INSERT INTO downloads(user_id,mod_id) VALUES(?,?)').bind(u?.id||null,b.mod_id).run()}if(b.pack_id){await env.DB.prepare('UPDATE packs SET downloads=downloads+1 WHERE id=?').bind(b.pack_id).run();await env.DB.prepare('INSERT INTO downloads(user_id,pack_id) VALUES(?,?)').bind(u?.id||null,b.pack_id).run()}await env.DB.prepare('UPDATE site_stats SET total_downloads=total_downloads+1 WHERE id=1').run();return json({ok:true},200,origin)}
if(path==='/api/admin/mods'&&method==='GET'){const u=await auth(req,env);if(u?.role!=='admin')return json({error:'forbidden'},403,origin);return json(await env.DB.prepare('SELECT * FROM mods ORDER BY id DESC').all(),200,origin)}
if(path==='/api/admin/mods'&&method==='POST'){const u=await auth(req,env);if(u?.role!=='admin')return json({error:'forbidden'},403,origin);const b=await req.json();await env.DB.prepare('INSERT INTO mods(title,description,category,version,image_url,download_url,featured) VALUES(?,?,?,?,?,?,?)').bind(b.title,b.description||'',b.category||'Other',b.version||'1.0',b.image_url||'',b.download_url||'#',b.featured?1:0).run();return json({ok:true},200,origin)}
if(path.startsWith('/api/admin/mods/')&&method==='DELETE'){const u=await auth(req,env);if(u?.role!=='admin')return json({error:'forbidden'},403,origin);await env.DB.prepare('DELETE FROM mods WHERE id=?').bind(path.split('/').pop()).run();return json({ok:true},200,origin)}
if(path==='/api/admin/users'&&method==='GET'){const u=await auth(req,env);if(u?.role!=='admin')return json({error:'forbidden'},403,origin);return json(await env.DB.prepare('SELECT id,username,email,role,created_at,last_login FROM users ORDER BY id DESC').all(),200,origin)}
return json({error:'not found'},404,origin)}
export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return await api(req,env);return env.ASSETS.fetch(req)}catch(e){return json({error:e.message},500,env.ALLOWED_ORIGIN||'*')}}};
