const headers={"content-type":"application/json;charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"Content-Type, Authorization","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS"};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers}); const now=()=>new Date().toISOString(); const id=()=>crypto.randomUUID();
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hp(p,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(s),iterations:100000,hash:'SHA-256'},k,256);return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function session(req,env){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return null;const raw=h.slice(7),r=await env.DB.prepare('SELECT s.*,u.email,u.name,u.role,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await sha(raw),now()).first();return r||null}
async function pub(env){const mods=await env.DB.prepare("SELECT id,title,description,category,version,image_url imageUrl,download_url downloadUrl,downloads FROM mods WHERE status='published' ORDER BY created_at DESC").all();const packs=await env.DB.prepare("SELECT id,title,description,category,version,image_url imageUrl,download_url downloadUrl,downloads FROM packs WHERE status='published' ORDER BY created_at DESC").all();const cats=await env.DB.prepare('SELECT id,name FROM categories ORDER BY sort_order').all();const st=await env.DB.prepare('SELECT users,mods,packs,downloads FROM site_stats WHERE id=1').first();return {mods:mods.results,packs:packs.results,categories:cats.results,stats:st}}
async function routes(req,env){const u=new URL(req.url),p=u.pathname,m=req.method;if(m==='OPTIONS')return new Response(null,{status:204,headers});
if(p==='/api/public'&&m==='GET')return out(await pub(env));
if(p==='/api/auth/register'&&m==='POST'){const b=await req.json(),email=String(b.email||'').trim().toLowerCase(),pass=String(b.password||''),name=String(b.name||'کاربر').trim();if(!email.includes('@')||pass.length<8)return out({error:'ایمیل یا رمز عبور معتبر نیست.'},400);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return out({error:'این ایمیل قبلاً ثبت شده است.'},409);const salt=id(),uid=id();await env.DB.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').bind(uid,email,name,await hp(pass,salt),salt,'user',now()).run();await env.DB.prepare('UPDATE site_stats SET users=users+1 WHERE id=1').run();const raw=id()+id();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').bind(id(),uid,await sha(raw),new Date(Date.now()+30*864e5).toISOString(),now()).run();return out({token:raw})}
if(p==='/api/auth/login'&&m==='POST'){const b=await req.json(),email=String(b.email||'').trim().toLowerCase(),u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||await hp(String(b.password||''),u.password_salt)!==u.password_hash)return out({error:'ایمیل یا رمز عبور اشتباه است.'},401);const raw=id()+id();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').bind(id(),u.id,await sha(raw),new Date(Date.now()+30*864e5).toISOString(),now()).run();return out({token:raw})}
if(p==='/api/auth/logout'&&m==='POST'){const s=await session(req,env);if(s)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(s.id).run();return out({ok:true})}
const s=await session(req,env);
if(p==='/api/me'&&m==='GET'){if(!s)return out({error:'ورود لازم است.'},401);const d=await env.DB.prepare('SELECT COUNT(*) n FROM downloads WHERE user_id=?').bind(s.user_id).first();return out({user:{id:s.user_id,email:s.email,name:s.name,role:s.role,createdAt:s.created_at,downloads:d.n}})}
if(p==='/api/me/downloads'&&m==='GET'){if(!s)return out({error:'ورود لازم است.'},401);const r=await env.DB.prepare('SELECT d.downloaded_at downloadedAt,m.title FROM downloads d JOIN mods m ON m.id=d.mod_id WHERE d.user_id=? ORDER BY d.downloaded_at DESC LIMIT 100').bind(s.user_id).all();return out({items:r.results})}
const dl=p.match(/^\/api\/mods\/([^/]+)\/download$/);if(dl&&m==='POST'){if(!s)return out({error:'برای ثبت دانلود وارد شوید.'},401);const mod=await env.DB.prepare("SELECT id,download_url FROM mods WHERE id=? AND status='published'").bind(dl[1]).first();if(!mod)return out({error:'مود پیدا نشد.'},404);await env.DB.prepare('INSERT INTO downloads VALUES(?,?,?,?)').bind(id(),s.user_id,mod.id,now()).run();await env.DB.prepare('UPDATE mods SET downloads=downloads+1 WHERE id=?').bind(mod.id).run();await env.DB.prepare('UPDATE site_stats SET downloads=downloads+1 WHERE id=1').run();return out({url:mod.download_url})}
if(p.startsWith('/api/admin/')){if(!s||s.role!=='admin')return out({error:'دسترسی مدیر لازم است.'},403);
if(p==='/api/admin/mods'&&m==='GET'){const r=await env.DB.prepare('SELECT id,title,description,category,version,image_url imageUrl,download_url downloadUrl,downloads,status FROM mods ORDER BY created_at DESC').all();return out({items:r.results})}
if(p==='/api/admin/mods'&&m==='POST'){const b=await req.json(),mid=b.id||id();if(!b.title||!b.downloadUrl)return out({error:'عنوان و لینک دانلود الزامی است.'},400);await env.DB.prepare(`INSERT INTO mods(id,title,description,category,version,image_url,download_url,downloads,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,description=excluded.description,category=excluded.category,version=excluded.version,image_url=excluded.image_url,download_url=excluded.download_url`).bind(mid,b.title,b.description||'',b.category||'عمومی',b.version||'',b.imageUrl||'',b.downloadUrl,0,'published',now()).run();await env.DB.prepare('UPDATE site_stats SET mods=(SELECT COUNT(*) FROM mods WHERE status="published") WHERE id=1').run();return out({ok:true})}
const md=p.match(/^\/api\/admin\/mods\/([^/]+)$/);if(md&&m==='DELETE'){await env.DB.prepare('DELETE FROM mods WHERE id=?').bind(md[1]).run();return out({ok:true})}
if(p==='/api/admin/packs'&&m==='POST'){const b=await req.json();if(!b.title||!b.downloadUrl)return out({error:'عنوان و لینک دانلود الزامی است.'},400);await env.DB.prepare('INSERT INTO packs VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id(),b.title,b.description||'',b.category||'پک',b.version||'',b.imageUrl||'',b.downloadUrl,0,'published',now()).run();await env.DB.prepare('UPDATE site_stats SET packs=(SELECT COUNT(*) FROM packs WHERE status="published") WHERE id=1').run();return out({ok:true})}
if(p==='/api/admin/sync-zargame'&&m==='POST'){const b=await req.json();if(!/^https?:\/\//.test(b.url||''))return out({error:'لینک معتبر نیست.'},400);const r=await fetch(b.url,{headers:{'user-agent':'Mozilla/5.0 EXE-PAK'}});if(!r.ok)return out({error:'صفحه قابل دریافت نیست.'},400);const h=await r.text();const g=re=>{const z=h.match(re);return z?z[1].trim():''};return out({title:g(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i)||g(/<title[^>]*>([\s\S]*?)<\/title>/i),description:g(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)/i),imageUrl:g(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i),downloadUrl:g(/href=["']([^"']+\.(?:zip|rar|7z)[^"']*)["']/i)})}
}if(env.ASSETS)return env.ASSETS.fetch(req);return out({error:'مسیر پیدا نشد.'},404)}
export default {async fetch(req,env){try{return await routes(req,env)}catch(e){return out({error:e.message||'خطای سرور'},500)}}}
